项目代码/AXF1806/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/", include('axf.urls', namespace='axf')),
    url(r"^axf/api/v1/", include('axf.urls_apis_v1', namespace='axfapi'))
]

项目代码/axf/urls.py
from django.conf.urls import url
from axf import views
urlpatterns=[
    url(r"^home$", views.home, name='home'),
    url(r"^market$", views.market, name='market'),
    url(r"^market-with-param/(\d+)/(\d+)/(\d+)", views.market_with_param, name='market_with_param'),
    url(r"^cart$", views.cart, name='cart'),
    url(r"^mine$", views.mine, name='mine'),
    url(r"^register$", views.RegisterAPI.as_view(), name="register"),
    url(r"^login$", views.LoginApi.as_view(), name="login"),
    url(r"^active/(.+)", views.active, name="active"),
    url(r"^logout$", views.LogoutAPI.as_view(), name="logout"),

]

项目代码/templates/mine/mine.html
{%extends 'base/base_main.html'%}
{%load static%}
{%block MyCSS%}
{{block.super}}
<link rel="stylesheet" href="{%static 'axf/mine/css/mine.css'%}">
{%endblock%}

{%block content%}
<div id="mine">
    <!--用户头部信息-->
    <div class="fixed">
        <!--<span class="glyphicon glyphicon-user"></span>-->
        {%if is_login%}
        <!--如果是登录 显示头像和用户名-->
        <span>
                    <img src="{{icon}}" alt="">
                </span>
        <p>{{username}}</p>
        {%else%}
        {#未登录 显示用户占位头像和未登录提示#}
        <span class="glyphicon glyphicon-user"></span>
        <p class="not_login">
            <a href="{%url 'axf:login'%}">未登录</a>
        </p>
        {%endif%}

        <p class="level">
            <span class="glyphicon glyphicon-fire"></span>
            <span>等级</span>
        </p>
        <p class="collect">
            <span class="glyphicon glyphicon-heart"></span>
            <span>收藏</span>
        </p>


    </div>
    {%if is_login%}
    {%else%}
    <div id="regis">
        <a href="{%url 'axf:register'%}">注册</a>
    </div>
    {%endif%}

    <!--我的订单-->
    <div class="mine_info">
        <p>
            我的订单
            <a href="#">查看全部订单&gt;</a>
        </p>

        <div id="nav">
            <ul>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-usd"></span>
                        </dt>
                        <dd>待付款</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-envelope"></span>
                        </dt>
                        <dd>待收货</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-pencil"></span>
                        </dt>
                        <dd>待评价</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-retweet"></span>
                        </dt>
                        <dd>退款/售后</dd>
                    </dl>
                </li>
            </ul>
        </div>

        <menu>
            <ul>
                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-bullhorn"></span>
                        </dt>
                        <dd>积分商城</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-credit-card"></span>
                        </dt>
                        <dd>优惠券</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-import"></span>
                        </dt>
                        <dd>收货地址</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-phone-alt"></span>
                        </dt>
                        <dd>客服反馈</dd>
                    </dl>
                </li>

                <li>
                    <dl>
                        <dt>
                            <span class="glyphicon glyphicon-phone-alt"></span>
                        </dt>
                        <dd>关于我们</dd>
                    </dl>
                </li>
            </ul>
        </menu>

        <!--退出登录-->
        <!--<p>-->
        <!--<a href="....">退出</a>-->
        <!--</p>-->

        {%if is_login%}
        <p>
            <a href="{%url 'axf:logout'%}">退出</a>
        </p>
        {%else%}

        {%endif%}
    </div>
</div>
{%endblock%}