项目代码/AXF1806/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^axf/", include('axf.urls', namespace='axf')),
    url(r"^axf/api/v1/", include('axf.urls_apis_v1', namespace='axfapi'))
]

项目代码/axf/urls.py
from django.conf.urls import url
from axf import views
urlpatterns=[
    url(r"^home$", views.home, name='home'),
    url(r"^market$", views.market, name='market'),
    url(r"^market-with-param/(\d+)/(\d+)/(\d+)", views.market_with_param, name='market_with_param'),
    url(r"^cart$", views.cart, name='cart'),
    url(r"^mine$", views.mine, name='mine'),
    url(r"^register$", views.RegisterAPI.as_view(), name="register"),
    url(r"^login$", views.LoginApi.as_view(), name="login"),
    url(r"^active/(.+)", views.active, name="active"),
    url(r"^logout$", views.LogoutAPI.as_view(), name="logout"),

]

项目代码/templates/base/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" href="{%static 'css/bootstrap.css'%}">
    <link rel="stylesheet" href="{%static 'css/swiper.css'%}">
    <link rel="stylesheet" href="{%static 'css/reset.css'%}">


    {%block MyCSS%}
    {%endblock%}
    <title>{{title}}</title>
</head>
<body>
<!--头部-->
{%block head%}
{%endblock%}
<!--内容区-->
{%block content%}
{%endblock%}
<!--底部导航栏-->
{%block footer%}
{%endblock%}
</body>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>


    {%block MyJs%}
    {%endblock%}
</html>

项目代码/templates/base/base_main.html
{% extends 'base/base.html' %}
{% load static %}

{% block MyCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}

{% block head %}
    <header></header>
{% endblock %}

{% block footer %}
    <footer>
        <a href="{% url 'axf:home' %}" class="home">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>
            </dl>
        </a>
        <a href="{% url 'axf:market' %}" class="market">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>
            </dl>
        </a>
        <a href="{% url 'axf:cart' %}" class="cart">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>
            </dl>
        </a>
        <a href="{% url 'axf:mine' %}" class="mine">
            <dl>
                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>
{% endblock %}

项目代码/templates/base/base_user.html
{%extends 'base/base.html'%}
{%load static%}
{%block MyCSS%}
    {{block.super}}
    <link rel="stylesheet" href="{%static 'axf/user/css/user.css'%}">
{%endblock%}
{%block head%}
    <header></header>
{%endblock%}
{%block MyJs%}
    {{block.super}}
    <script type="text/javascript" src="{%static 'js/md5.js'%}"></script>
{%endblock%}